---
title: "Task 2 - Palmetto binary logistic regression"
author: "Larissa Neilson"
date: "2/5/2021"
output:
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
	warning = FALSE
)
library(tidyverse)
library(here)
library(janitor)
library(GGally)
library(broom)
library(jtools)
```

```{r}
# Read in data
palmetto <- read_csv(here("data", "palmetto.csv"),
                     col_types = cols(.default = "c")) %>%
  mutate(height = as.numeric(height)) %>%
  mutate(length = as.numeric(length)) %>%
  mutate(width = as.numeric(width)) %>% 
  mutate(green_lvs = as.numeric(green_lvs)) %>% 
  clean_names()
```

```{r}
# Create smaller subset to work with
palmetto_new <- palmetto %>% 
  select(species, height, length, width, green_lvs)
```

```{r}
# Visualize the data
ggplot(data = palmetto_new, aes(x = height, y = length)) +
  geom_point(aes(color = species)) +
  labs(x = "Height (cm)", y = "Length (cm)") +
  theme_minimal()
```

```{r}
ggplot(data = palmetto_new, aes(x = height, y = width)) +
  geom_point(aes(color = species)) +
  labs(x = "Height (cm)", y = "Width (cm)") +
  theme_minimal()
```

```{r}
ggplot(data = palmetto_new, aes(x = height, y = green_lvs)) +
  geom_col(aes(color = species)) +
  labs(x = "Height (cm)", y = "Green Leaf Count") +
  theme_minimal()
```



#### Data citation

Abrahamson, W.G. 2019. Survival, growth and biomass estimates of two dominant palmetto species of south-central Florida from 1981 - 2017, ongoing at 5-year intervals ver 1. Environmental Data Initiative. https://doi.org/10.6073/pasta/f2f96ec76fbbd4b9db431c79a770c4d5

